# Multistage for lean production release

FROM golang:1.19 AS build-stage
WORKDIR /rewild

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /rewild-api ./cmd/server.go

# Deploy the application binary into a lean image
FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /rewild-api /rewild-api

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/rewild-api"]